basePath: /api/v1
definitions:
  Api.pong:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a calculation server.
  title: Calculation Server API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Api.pong'
      summary: ping to check a server
      tags:
      - ping
swagger: "2.0"
