version: '3.8'
services:
  ant-db:
    env_file:
      - postgresql.env
    image: postgres:16
    ports:
      - 5432:5432

  ant-storage:
    env_file:
      - storage/.env
    build: ./storage
    ports:
      - 8080:8080
      - 50051:50051
    depends_on:
      - ant-db
      - ant-calculation-server
      - ant-ui-storage

  ant-calculation-server:
    env_file:
      - calculationServer/.env
    build: ./calculationServer

  ant-ui-storage:
    env_file:
      - ui-storage/.env
    build: ./ui-storage
    ports:
      - 3000:3000
